// <auto-generated />
using System;
using CouponService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CouponService.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113162152_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CouponService.API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CouponName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50m,
                            CouponName = "OkkMF50",
                            ExpiryDate = new DateTime(2025, 1, 18, 17, 21, 51, 565, DateTimeKind.Local).AddTicks(2540),
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100m,
                            CouponName = "OkkMF100",
                            ExpiryDate = new DateTime(2025, 1, 23, 17, 21, 51, 565, DateTimeKind.Local).AddTicks(2587),
                            IsEnabled = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
